language: node_js
dist: trusty
node_js:
  - "8"
addons:
  apt:
    packages:
      - "python"
      - "python3"
      - "python-pip"
      - "python3-pip"
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
install:
  - python -m pip install --user --upgrade -r requirements.txt
  - python3 -m pip install --user --upgrade -r requirements.txt
  - npm install
before_script:
  - npm run lint
  - npm audit
