language: python

env:
  global:
    - ENABLE_TEST_LOGGING=1

matrix:
  include:
    - os: linux
      dist: xenial
      python: "2.7"
      env: TOXENV=py27
    - os: linux
      dist: xenial
      python: "3.6"
      env: TOXENV=py36
    - os: linux
      dist: xenial
      python: "3.7"
      env: TOXENV=py37
    - os: osx
      language: generic
      env: PYTHON=2.7 TOXENV=py27
    - os: osx
      language: generic
      env: PYTHON=3.6 TOXENV=py36
    - os: osx
      language: generic
      env: PYTHON=3.7.3 TOXENV=py37
services:
  - xvfb
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sleep 3;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update;
      brew upgrade pyenv;
      pyenv install $PYTHON;
      pyenv local $PYTHON;
      python --version;
    fi

install:
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade tox setuptools
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install 8.9.1
  - nvm use 8.9.1
  - npm install npm@latest -g
  - npm ci

before_script:
  - npm run lint
  - travis_retry npm audit

script:
  - tox -e $TOXENV
